services:
    amplify:
        build: ./
        container_name: amplify
        ports: 
            - "3000:3000"
            - "20002:20002"
        volumes:
            - .:/var/www/app
        tty: true
